# Generated by Django 4.1 on 2023-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0003_alter_prepare_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
