# Generated by Django 4.1 on 2023-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0006_invoice_invoice_date_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Valider', 'Paye'), ('Refuser', 'Annuler'), ('En Attend', 'pendig')], default='pending', max_length=10),
        ),
    ]
