# Generated by Django 4.1 on 2023-11-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0007_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovisinenemt',
            name='order',
            field=models.OneToOneField(limit_choices_to={'status': 'En Attend'}, on_delete=django.db.models.deletion.CASCADE, to='orderItem.validate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Paye', 'Paye'), ('Annuler', 'Annuler'), (' Pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
