# Generated by Django 5.0 on 2023-12-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0015_alter_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
